import type { NextConfig } from 'next';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { legacyRedirects } from './src/lib/legacy-routes';

/**
 * Legacy → new URL map, generated by `scripts/build-redirects.ts` and reviewed in PR.
 * This is the safeguard for ~180 pages of existing SEO equity. Every entry is 1:1
 * and permanent; wildcard-to-homepage redirects are forbidden (see DEVELOPMENT-PLAN §6).
 */
type RedirectEntry = { source: string; destination: string; permanent?: boolean };

function loadRedirects(): RedirectEntry[] {
  try {
    const raw = readFileSync(join(process.cwd(), 'redirects.json'), 'utf8');
    const parsed: unknown = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed as RedirectEntry[];
  } catch {
    return [];
  }
}

const securityHeaders = [
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
  { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,

  outputFileTracingExcludes: {
    '/api/**/*': [
      'node_modules/@xenova/**',
      'node_modules/onnxruntime-node/**',
      'node_modules/onnxruntime-common/**',
      'node_modules/onnxruntime-web/**',
      'node_modules/sharp/**',
    ],
  },

  serverExternalPackages: ['@xenova/transformers'],

  experimental: {
    optimizePackageImports: ['lucide-react'],
  },

  // Hosting-agnostic: no platform-specific adapters in the core build.
  // `output: 'standalone'` keeps a self-hosted Node/Docker deploy open as an option.
  output: process.env.BUILD_STANDALONE === 'true' ? 'standalone' : undefined,

  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: [
      // CMS asset host gets added here once the CMS is chosen.
      { protocol: 'https', hostname: '**.sanity.io' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
      // Legacy Jetking / ClickFunnels covers used by migrated blog posts.
      { protocol: 'https', hostname: 'images.clickfunnels.com' },
      { protocol: 'https', hostname: 'statics.myclickfunnels.com' },
      { protocol: 'https', hostname: 'www.jetking.com' },
    ],
  },

  typedRoutes: true,

  async redirects() {
    const reviewed = loadRedirects();
    const merged = new Map<string, { source: string; destination: string; permanent: boolean }>();

    for (const entry of [...legacyRedirects, ...reviewed]) {
      merged.set(entry.source, {
        source: entry.source,
        destination: entry.destination,
        permanent: entry.permanent ?? true,
      });
    }

    return [...merged.values()];
  },

  async headers() {
    return [{ source: '/:path*', headers: securityHeaders }];
  },
};

export default nextConfig;
